name: tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ocvalidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: brokeyourbike/ocvalidate-action@v0.3
        with:
          opencore-version: '0.9.9'
          release: true

      - run: ocvalidate ./OC/config.plist
